// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq-uFNew0WIKIlVG_i_czHh9oGQS3f-pw',
    appId: '1:918655092924:web:2be56bc5a67503eea1a8b9',
    messagingSenderId: '918655092924',
    projectId: 'amm-stareducationcentre',
    authDomain: 'amm-stareducationcentre.firebaseapp.com',
    storageBucket: 'amm-stareducationcentre.appspot.com',
    measurementId: 'G-G3DNQW16R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYyMVlBOJ6fbGx_5YwinVuESFOj4AKLjU',
    appId: '1:918655092924:android:753b7d07e0eb4b94a1a8b9',
    messagingSenderId: '918655092924',
    projectId: 'amm-stareducationcentre',
    storageBucket: 'amm-stareducationcentre.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrdVu_FybaI3j0JWKrBV0phQmEPsOAhzM',
    appId: '1:918655092924:ios:cb0c0bb11049f735a1a8b9',
    messagingSenderId: '918655092924',
    projectId: 'amm-stareducationcentre',
    storageBucket: 'amm-stareducationcentre.appspot.com',
    iosBundleId: 'com.starEducation.starEducationCentre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrdVu_FybaI3j0JWKrBV0phQmEPsOAhzM',
    appId: '1:918655092924:ios:cb0c0bb11049f735a1a8b9',
    messagingSenderId: '918655092924',
    projectId: 'amm-stareducationcentre',
    storageBucket: 'amm-stareducationcentre.appspot.com',
    iosBundleId: 'com.starEducation.starEducationCentre',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq-uFNew0WIKIlVG_i_czHh9oGQS3f-pw',
    appId: '1:918655092924:web:f20cbd2153c5dee0a1a8b9',
    messagingSenderId: '918655092924',
    projectId: 'amm-stareducationcentre',
    authDomain: 'amm-stareducationcentre.firebaseapp.com',
    storageBucket: 'amm-stareducationcentre.appspot.com',
    measurementId: 'G-LWKFXW1KQM',
  );
}
